# Generated by Django 2.0.2 on 2018-04-10 18:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import thursdays.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('email_one', models.EmailField(max_length=254)),
                ('email_two', models.EmailField(blank=True, max_length=254, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=thursdays.models.company_directory_path)),
                ('ppt', models.FileField(blank=True, null=True, upload_to=thursdays.models.company_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['ppt', 'pptx'])])),
                ('is_registered', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Thursday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('scheduled', models.BooleanField(default=False)),
                ('is_currently_available', models.BooleanField(default=True)),
                ('assigned_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='thursdays.Company')),
            ],
            options={
                'verbose_name_plural': 'Pizza My Mind Dates',
                'ordering': ['date'],
            },
        ),
        migrations.AddField(
            model_name='company',
            name='pmm_date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='thursdays.Thursday'),
        ),
    ]
